# 项目唯一标识符
sonar.projectKey=sdrui
# 项目名称
sonar.projectName=special-discount-request-ui
# 项目版本
sonar.projectVersion=1.0
# 源代码目
sonar.sources=productmanagement/webapp
sonar.exclusions=productmanagement/webapp/test/**
sonar.host.url=http://localhost:9004
sonar.login=2216390672181f9d09b3cb58a1332ab8e7dd333b
sonar.javascript.lcov.reportPaths=productmanagement/coverage/lcov.info